using TaskManagerAPI.Entities;
using TaskManagerAPI.Models.DTOs;
using TaskManagerAPI.Repositories;

namespace TaskManagerAPI.Services
{
    public class TaskService(ITaskRepository repository) : ITaskService
    {
        private readonly ITaskRepository _repository = repository;

        public async Task<TaskEntity> CreateTaskAsync(TaskCreateRequest requestDto)
        {
            var task = new TaskEntity
            {
                //Id = 1; Auto-generated by EF ORM
                Title = requestDto.Title,
                Description = requestDto.Description,
                UserId = requestDto.UserId,
                CreatedDate = DateTime.UtcNow,
                LastUpdated = DateTime.UtcNow,
            };

            return await _repository.AddTaskAsync(task);
        }

        public async Task<TaskEntity?> GetTask(int Id)
        {
            return await _repository.GetTask(Id);
        }

        public async Task<List<TaskEntity>> GetTasksByUserId(int userId)
        {
            return await _repository.GetTasksByUserId(userId);
        }
    }
}
